version: '3.4'

services:
  app: 
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      RAILS_ENV: development
    command: ['rails', 'server', '-p', '3000', '-b', '0.0.0.0']
